modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "GNU GPL"

[[mods]]
modId = "rnf"
version = "${version}"
displayName = "RNF"
authors = "Bob Dole"
description = '''
This is a mod for RNF
'''
logoFile = "assets/rnf/icon.png"

[[dependencies.rnf]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rnf]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rnf]]
modId = "architectury"
mandatory = true
versionRange = "[4.0.29,)"
ordering = "AFTER"
side = "BOTH"